package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.util.*;import java.util.regex.*;
public class DocumentDiagnosticActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Diagnostic du catalogue",27,true));String id=getIntent().getStringExtra("id");DocumentStore.Item d=DocumentStore.find(this,id);if(d==null){r.addView(Ui.text(this,"Catalogue introuvable.",14,false));setContentView(Ui.wrap(this,r));return;}try{List<List<String>> rows=DocumentStore.read(this,d);List<DataNormalizer.ColumnMapping> maps=DocumentStore.readMappings(this,d);int mapped=0,validated=0,unmapped=0;for(DataNormalizer.ColumnMapping m:maps){if(m.targetField!=null&&!m.targetField.isBlank())mapped++;else unmapped++;if(m.humanValidated)validated++;}int coverage=maps.isEmpty()?0:(int)Math.round(mapped*100.0/maps.size());int human=maps.isEmpty()?0:(int)Math.round(validated*100.0/maps.size());int blankHeaders=0,dupHeaders=0,badDates=0;if(!rows.isEmpty()){Set<String> seen=new HashSet<>();for(String h:rows.get(0)){String x=h==null?"":h.trim().toLowerCase(Locale.ROOT);if(x.isEmpty())blankHeaders++;else if(!seen.add(x))dupHeaders++;}for(int c=0;c<rows.get(0).size();c++){String h=rows.get(0).get(c).toLowerCase(Locale.ROOT);if(h.contains("date")||h.contains("debut")||h.contains("fin")){for(int i=1;i<rows.size();i++){String v=c<rows.get(i).size()?rows.get(i).get(c).trim():"";if(!v.isEmpty()&&!looksDate(v))badDates++;}}}}
 LinearLayout p=Ui.panel(this);p.addView(Ui.text(this,d.name,21,true));p.addView(Ui.text(this,"Fiches : "+d.rows+"\nColonnes : "+d.columns+"\nQualité interne : "+d.score+" %\nCellules vides : "+d.emptyCells+"\nDoublons : "+d.duplicates+"\nCorrections automatiques : "+d.changedCells,14,false));r.addView(p);
 LinearLayout m=Ui.panel(this);m.addView(Ui.text(this,"Couverture de cartographie",20,true));m.addView(Ui.text(this,"Champs cartographiés : "+mapped+" / "+maps.size()+" ("+coverage+" %)\nValidations humaines : "+validated+" / "+maps.size()+" ("+human+" %)\nSans cible : "+unmapped,14,false));r.addView(m);
 LinearLayout f=Ui.panel(this);f.addView(Ui.text(this,"Anomalies de structure et format",20,true));f.addView(Ui.text(this,"En-têtes vides : "+blankHeaders+"\nEn-têtes dupliqués : "+dupHeaders+"\nValeurs de date à vérifier : "+badDates,14,false));r.addView(f);
 boolean pass=unmapped==0&&validated==maps.size()&&blankHeaders==0&&dupHeaders==0&&badDates==0&&d.duplicates==0;LinearLayout s=Ui.panel(this);s.addView(Ui.text(this,pass?"DIAGNOSTIC INTERNE COMPLET":"CORRECTIONS REQUISES",21,true));s.addView(Ui.text(this,pass?"Aucune anomalie détectée par les contrôles internes actuels.":"Corriger les éléments ci-dessus puis relancer le diagnostic. Ce contrôle n’est pas une certification sectorielle.",13,false));r.addView(s);Button map=Ui.primary(this,"Ouvrir la cartographie");map.setOnClickListener(v->{Intent i=new Intent(this,MappingActivity.class);i.putExtra("id",d.id);startActivity(i);});r.addView(map);}catch(Exception e){r.addView(Ui.text(this,"Erreur de diagnostic : "+e.getMessage(),14,false));}setContentView(Ui.wrap(this,r));}
 private boolean looksDate(String v){return Pattern.matches("\\d{4}-\\d{2}-\\d{2}([T ][0-2]\\d:[0-5]\\d(:[0-5]\\d)?)?",v)||Pattern.matches("\\d{1,2}[/.-]\\d{1,2}[/.-]\\d{4}",v);}
}
