package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.util.*;
public class EvaluationCriteriaActivity extends Activity{
 private SharedPreferences p;
 private final String[] generalKeys={"g_alignment","g_data_plan","g_team"};
 private final String[] generalLabels={"Concordance avec la finalité et les objectifs du programme","Qualité du plan de gestion des données descriptives","Expérience et compétence de l’équipe, incluant les ressources externes"};
 private final int[] generalWeights={35,30,35};
 private final String[] specificKeys={"s_standard","s_clarity","s_capacity","s_feasibility","s_budget","s_technology","s_sustainability","s_ecosystem"};
 private final String[] specificLabels={"Respect des normes sectorielles reconnues","Clarté et précision du projet","Capacité du demandeur à réaliser le projet","Faisabilité et réalisme du projet et du calendrier","Réalisme et qualité du budget","Qualité et pertinence de l’approche technologique","Principes de développement durable","Répercussions sur la qualité des données de l’écosystème"};
 private final int[] specificWeights={15,10,15,15,15,10,5,15};
 private TextView summary;
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);p=getSharedPreferences("evaluation_score",0);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Grille d’évaluation",27,true));r.addView(Ui.text(this,"Simulation interne basée sur les pondérations officielles. Une note interne ne prédit pas la décision du Ministère.",13,false));summary=Ui.text(this,"",16,true);r.addView(summary);addGroup(r,"Analyse générale — seuil officiel de 70 %",generalKeys,generalLabels,generalWeights);addGroup(r,"Analyse spécifique",specificKeys,specificLabels,specificWeights);LinearLayout bonus=Ui.panel(this);bonus.addView(Ui.text(this,"Bonus potentiels",20,true));CheckBox regional=new CheckBox(this);regional.setText("Siège hors des communautés métropolitaines de Québec et Montréal : bonus officiel de 10 %");regional.setChecked(p.getBoolean("bonus_region",false));regional.setOnCheckedChangeListener((v,x)->{p.edit().putBoolean("bonus_region",x).apply();refresh();});bonus.addView(regional);CheckBox open=new CheckBox(this);open.setText("Dépôt régulier des données descriptives en données ouvertes : bonus officiel de 5 %");open.setChecked(p.getBoolean("bonus_open",false));open.setOnCheckedChangeListener((v,x)->{p.edit().putBoolean("bonus_open",x).apply();refresh();});bonus.addView(open);r.addView(bonus);LinearLayout notes=Ui.panel(this);notes.addView(Ui.text(this,"Points à documenter",20,true));notes.addView(Ui.text(this,"Développement durable : réduction des doubles saisies, réutilisation des données, pérennité des formats, maintenance raisonnable et pratiques responsables.\n\nImpact écosystème : meilleure qualité, interopérabilité, partage, découvrabilité, réutilisation par des partenaires et suivi mesurable des données standardisées.",14,false));r.addView(notes);Button done=Ui.secondary(this,"Retour");done.setOnClickListener(v->finish());r.addView(done);refresh();setContentView(Ui.wrap(this,r));}
 private void addGroup(LinearLayout root,String title,String[] keys,String[] labels,int[] weights){LinearLayout box=Ui.panel(this);box.addView(Ui.text(this,title,20,true));for(int i=0;i<keys.length;i++){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.addView(Ui.text(this,labels[i]+" — "+weights[i]+" %",14,true));SeekBar s=new SeekBar(this);s.setMax(100);s.setProgress(p.getInt(keys[i],0));TextView val=Ui.text(this,s.getProgress()+" / 100",13,false);final String k=keys[i];s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int progress,boolean from){val.setText(progress+" / 100");p.edit().putInt(k,progress).apply();refresh();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});row.addView(s);row.addView(val);box.addView(row);}root.addView(box);}
 private double score(String[] keys,int[] w){double total=0;for(int i=0;i<keys.length;i++)total+=p.getInt(keys[i],0)*w[i]/100.0;return total;}
 private void refresh(){if(summary==null)return;double g=score(generalKeys,generalWeights),s=score(specificKeys,specificWeights);int bonus=(p.getBoolean("bonus_region",false)?10:0)+(p.getBoolean("bonus_open",false)?5:0);summary.setText(String.format(Locale.CANADA_FRENCH,"Analyse générale : %.1f / 100 — %s\nAnalyse spécifique : %.1f / 100\nBonus potentiels : +%d points",g,g>=70?"seuil interne atteint":"sous le seuil officiel de 70 %",s,bonus));}
}