package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import java.util.zip.*;
public class ExportPackageActivity extends Activity{
 private static final int CREATE_ZIP=4401;private byte[] pending;
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Exporter le dossier final",27,true));r.addView(Ui.text(this,"Crée une archive ZIP locale contenant le résumé du projet, les catalogues normalisés, les cartographies et les audits disponibles. Aucun fichier n’est envoyé automatiquement à un serveur.",13,false));LinearLayout p=Ui.panel(this);p.addView(Ui.text(this,"Contenu de l’archive",20,true));p.addView(Ui.text(this,"• resume-projet.txt\n• pieces-justificatives.txt\n• catalogues/*.csv\n• mappings/*.json\n• audits/*.json quand disponibles",14,false));r.addView(p);Button make=Ui.primary(this,"Créer et enregistrer le ZIP");make.setOnClickListener(v->createZip());r.addView(make);Button back=Ui.secondary(this,"Retour au contrôle final");back.setOnClickListener(v->finish());r.addView(back);r.addView(Ui.text(this,"L’archive est une aide de préparation interne. Vérifier les exigences du programme et les documents officiels avant un dépôt.",12,false));setContentView(Ui.wrap(this,r));}
 private void createZip(){try{pending=buildZip();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");String d=new SimpleDateFormat("yyyy-MM-dd_HHmm",Locale.CANADA_FRENCH).format(new Date());i.putExtra(Intent.EXTRA_TITLE,"Culture-du-Quebec-dossier-"+d+".zip");startActivityForResult(i,CREATE_ZIP);}catch(Exception e){Toast.makeText(this,"Erreur export : "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req!=CREATE_ZIP||res!=RESULT_OK||data==null||data.getData()==null||pending==null)return;Uri u=data.getData();try(OutputStream out=getContentResolver().openOutputStream(u)){out.write(pending);out.flush();Toast.makeText(this,"Dossier ZIP enregistré",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Impossible d’enregistrer : "+e.getMessage(),Toast.LENGTH_LONG).show();}finally{pending=null;}}
 private byte[] buildZip()throws Exception{ByteArrayOutputStream mem=new ByteArrayOutputStream();try(ZipOutputStream z=new ZipOutputStream(mem,StandardCharsets.UTF_8)){put(z,"resume-projet.txt",summary().getBytes(StandardCharsets.UTF_8));put(z,"pieces-justificatives.txt",supporting().getBytes(StandardCharsets.UTF_8));for(DocumentStore.Item d:DocumentStore.list(this)){String base=safe(d.name.isBlank()?d.id:d.name);File csv=new File(getFilesDir(),d.fileName);if(csv.exists())putFile(z,"catalogues/"+base+".csv",csv);if(d.mappingFile!=null&&!d.mappingFile.isBlank()){File m=new File(getFilesDir(),d.mappingFile);if(m.exists())putFile(z,"mappings/"+base+"-mapping.json",m);}File a=new File(getFilesDir(),d.id+"-mapping-audit.json");if(a.exists())putFile(z,"audits/"+base+"-audit.json",a);}}return mem.toByteArray();}
 private void put(ZipOutputStream z,String name,byte[] data)throws Exception{ZipEntry e=new ZipEntry(name);z.putNextEntry(e);z.write(data);z.closeEntry();}
 private void putFile(ZipOutputStream z,String name,File f)throws Exception{ZipEntry e=new ZipEntry(name);z.putNextEntry(e);try(InputStream in=new FileInputStream(f)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)z.write(b,0,n);}z.closeEntry();}
 private String safe(String s){String x=s.replaceAll("[^A-Za-z0-9._-]+","-");return x.isBlank()?"catalogue":x;}
 private String summary(){SharedPreferences plan=getSharedPreferences("standardisation_plan",0),budget=getSharedPreferences("budget",0),team=getSharedPreferences("team_capacity",0),timeline=getSharedPreferences("timeline",0),check=getSharedPreferences("application_checklist",0);String[] standards={"MétaMusique","Arts de la scène","Cinéma","Livre — éditeurs","Exposition dans un contexte muséal"};int si=Math.max(0,Math.min(4,plan.getInt("standard",0)));int checked=0;for(int i=0;i<14;i++)if(check.getBoolean("i"+i,false))checked++;StringBuilder s=new StringBuilder("CULTURE DU QUÉBEC — DOSSIER EXPORTÉ\n\n");s.append("Organisation : ").append(plan.getString("org","—")).append("\nNorme : ").append(standards[si]).append("\nResponsable données : ").append(plan.getString("resp","—")).append("\nSources : ").append(plan.getString("sources","—")).append("\nContrôle qualité : ").append(plan.getString("quality","—")).append("\nPartage : ").append(plan.getString("sharing","—")).append("\nSauvegarde : ").append(plan.getString("backup","—")).append("\nCible : ").append(plan.getString("target","—")).append("\nÉchéancier global : ").append(plan.getString("schedule","—")).append("\n\nBudget total : ").append(String.format(Locale.CANADA_FRENCH,"%.2f $",budget.getFloat("total",0f))).append("\nAide théorique max : ").append(String.format(Locale.CANADA_FRENCH,"%.2f $",budget.getFloat("aid",0f))).append("\nChef de projet : ").append(team.getString("chef","—")).append("\nCompétences : ").append(team.getString("competences","—")).append("\nChecklist : ").append(checked).append(" / 14\nPièces : ").append(SupportingDocumentsActivity.completedCount(this)).append(" / 11\nCatalogues : ").append(DocumentStore.list(this).size()).append("\n\nÉCHÉANCIER\n");String[] phases={"Inventaire et sauvegarde","Cartographie","Nettoyage et normalisation","Validation humaine","Export et documentation","Partage / données ouvertes","Mesure et reddition"};for(int i=0;i<phases.length;i++)s.append("- ").append(phases[i]).append(" : ").append(timeline.getString("months"+i,"—")).append(" · ").append(timeline.getString("note"+i,"—")).append(timeline.getBoolean("done"+i,false)?" [fait]":"").append('\n');s.append("\nCe fichier est un résumé interne et non une certification officielle.\n");return s.toString();}
 private String supporting(){SharedPreferences p=getSharedPreferences("supporting_docs",0);String[] k={"quote","capacity","budget","timeline","data_plan","catalog_sample","mapping_audit","team","risks","open_data","official_forms"};String[] l={"Devis fournisseur / estimation","Preuve de capacité interne","Budget détaillé","Échéancier","Plan de gestion des données","Échantillon catalogue","Audit de cartographie","Équipe et compétences","Registre des risques","Partage / données ouvertes","Formulaires officiels"};StringBuilder s=new StringBuilder("PIÈCES JUSTIFICATIVES\n\n");for(int i=0;i<k.length;i++)s.append(p.getBoolean(k[i],false)?"[OK] ":"[À FOURNIR] ").append(l[i]).append('\n');return s.toString();}
}
