package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.zip.*;
public class FinalExportActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Export final du dossier",27,true));r.addView(Ui.text(this,"Centralise les exports du projet et les dernières vérifications avant partage ou dépôt.",13,false));Button pdf=Ui.primary(this,"Créer le PDF du dossier");pdf.setOnClickListener(v->startActivity(new Intent(this,PdfExportActivity.class)));r.addView(pdf);Button make=Ui.primary(this,"Créer le ZIP du dossier");make.setOnClickListener(v->exportZip());r.addView(make);Button pieces=Ui.secondary(this,"Vérifier les pièces justificatives");pieces.setOnClickListener(v->startActivity(new Intent(this,SupportingDocumentsActivity.class)));r.addView(pieces);Button state=Ui.secondary(this,"Vérifier l’état du dossier");state.setOnClickListener(v->startActivity(new Intent(this,GrantReadinessActivity.class)));r.addView(state);Button privacy=Ui.secondary(this,"Confidentialité et données");privacy.setOnClickListener(v->startActivity(new Intent(this,PrivacyActivity.class)));r.addView(privacy);r.addView(Ui.text(this,"Les exports sont des dossiers de travail. Ils ne remplacent pas les formulaires ni une décision officielle.",12,false));setContentView(Ui.wrap(this,r));}
 private void exportZip(){try{File dir=new File(getExternalFilesDir(null),"exports");dir.mkdirs();File out=new File(dir,"Culture-du-Quebec-dossier-"+System.currentTimeMillis()+".zip");ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out));put(z,"README.txt","CULTURE DU QUÉBEC — DOSSIER DE TRAVAIL\nArchive générée par l’application. Vérifier les exigences officielles avant dépôt.\n");put(z,"etat-pieces.txt",pieces());put(z,"catalogues.txt",catalogues());put(z,"projet.txt",project());z.close();Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/zip");i.putExtra(Intent.EXTRA_SUBJECT,"Culture du Québec — dossier exporté");i.putExtra(Intent.EXTRA_TEXT,"Archive créée dans le stockage privé de l’application : "+out.getName());startActivity(Intent.createChooser(i,"Archive créée — partager l’information"));Toast.makeText(this,"ZIP créé : "+out.getName(),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export impossible : "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void put(ZipOutputStream z,String name,String text)throws Exception{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(java.nio.charset.StandardCharsets.UTF_8));z.closeEntry();}
 private String pieces(){int n=SupportingDocumentsActivity.completedCount(this);return "PIÈCES JUSTIFICATIVES\nDisponibles : "+n+" / 10\nJeu complet : "+(SupportingDocumentsActivity.isComplete(this)?"oui":"non")+"\n";}
 private String catalogues(){StringBuilder s=new StringBuilder("CATALOGUES\n");List<DocumentStore.Item> docs=DocumentStore.list(this);for(DocumentStore.Item d:docs){int map=0,val=0;try{for(DataNormalizer.ColumnMapping m:DocumentStore.readMappings(this,d)){if(m.targetField!=null&&!m.targetField.isBlank())map++;if(m.humanValidated)val++;}}catch(Exception ignored){}s.append("- ").append(d.name).append(" | fiches ").append(d.rows).append(" | cartographies ").append(map).append(" | validations ").append(val).append(" | corrections ").append(d.changedCells).append(" | doublons ").append(d.duplicates).append('\n');}return s.toString();}
 private String project(){SharedPreferences p=getSharedPreferences("standardisation_plan",0);SharedPreferences b=getSharedPreferences("budget",0);SharedPreferences c=getSharedPreferences("application_checklist",0);int done=0;for(int i=0;i<14;i++)if(c.getBoolean("i"+i,false))done++;return "PROJET\nOrganisation : "+p.getString("org","—")+"\nResponsable données : "+p.getString("resp","—")+"\nCible : "+p.getString("target","—")+"\nÉchéancier : "+p.getString("schedule","—")+"\nBudget total : "+String.format(Locale.CANADA_FRENCH,"%.2f $",b.getFloat("total",0f))+"\nChecklist : "+done+" / 14\n";}
}
