package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.util.*;
public class GrantReadinessActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"État du dossier",27,true));r.addView(Ui.text(this,"Détection interne des éléments prêts, incomplets et bloquants avant de transférer l’information vers les formulaires officiels.",13,false));List<String> ready=new ArrayList<>(), incomplete=new ArrayList<>(), blockers=new ArrayList<>();evaluate(ready,incomplete,blockers);LinearLayout summary=Ui.panel(this);summary.addView(Ui.text(this,"Résumé",21,true));int total=ready.size()+incomplete.size()+blockers.size();int score=total==0?0:(int)Math.round(ready.size()*100.0/total);summary.addView(Ui.text(this,"Préparation documentaire : "+score+" %\nPrêts : "+ready.size()+" · Incomplets : "+incomplete.size()+" · Bloquants : "+blockers.size(),16,true));summary.addView(Ui.text(this,blockers.isEmpty()?"Aucun blocage interne détecté. Une vérification officielle demeure requise.":"Le dossier comporte au moins un élément bloquant à corriger.",13,false));r.addView(summary);addGroup(r,"BLOQUANTS",blockers,"Aucun blocage détecté.");addGroup(r,"INCOMPLETS",incomplete,"Aucun élément incomplet.");addGroup(r,"PRÊTS",ready,"Aucun élément marqué prêt.");Button share=Ui.primary(this,"Partager l’état du dossier");share.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"Culture du Québec — état du dossier");i.putExtra(Intent.EXTRA_TEXT,render(ready,incomplete,blockers));startActivity(Intent.createChooser(i,"Partager"));});r.addView(share);r.addView(Ui.text(this,"Cet écran ne détermine ni l’admissibilité ni l’obtention d’une aide financière. Les règles et formulaires du Ministère demeurent la référence.",12,false));setContentView(Ui.wrap(this,r));}
 private void evaluate(List<String> ready,List<String> incomplete,List<String> blockers){SharedPreferences plan=getSharedPreferences("standardisation_plan",0);String org=plan.getString("org","").trim(),resp=plan.getString("resp","").trim();if(org.isEmpty())blockers.add("Organisation non renseignée.");else ready.add("Organisation renseignée.");if(resp.isEmpty())incomplete.add("Responsable des données à renseigner.");else ready.add("Responsable des données identifié.");String[] planKeys={"sources","quality","sharing","backup","target","schedule"};String[] planLabels={"Sources et provenance","Contrôle qualité","Partage / données ouvertes","Sauvegardes et conservation","Cible mesurable","Échéancier global"};for(int i=0;i<planKeys.length;i++){if(plan.getString(planKeys[i],"").trim().isEmpty())incomplete.add(planLabels[i]+" à compléter.");else ready.add(planLabels[i]+" documenté.");}
 List<DocumentStore.Item> docs=DocumentStore.list(this);if(docs.isEmpty())blockers.add("Aucun catalogue importé : impossible de démontrer une mise à niveau réelle de données.");else ready.add(docs.size()+" catalogue(s) importé(s).");int mappings=0,validated=0,unmapped=0;for(DocumentStore.Item d:docs)try{for(DataNormalizer.ColumnMapping m:DocumentStore.readMappings(this,d)){if(m.targetField!=null&&!m.targetField.isBlank())mappings++;else unmapped++;if(m.humanValidated)validated++;}}catch(Exception e){incomplete.add("Audit de cartographie illisible pour "+d.name+".");}if(!docs.isEmpty()&&mappings==0)blockers.add("Aucune correspondance de champs enregistrée.");else if(mappings>0)ready.add(mappings+" correspondance(s) de champs enregistrée(s).");if(mappings>0&&validated==0)blockers.add("Aucune correspondance validée humainement.");else if(validated>0)ready.add(validated+" correspondance(s) validée(s) humainement.");if(unmapped>0)incomplete.add(unmapped+" colonne(s) restent sans cible.");
 SharedPreferences budget=getSharedPreferences("budget",0);float total=budget.getFloat("total",0f);if(total<=0)blockers.add("Budget non préparé ou total égal à 0 $.");else{ready.add("Budget préparé : "+String.format(java.util.Locale.CANADA_FRENCH,"%.2f $",total));double training=num(budget.getString("training","0")),admin=num(budget.getString("admin","0")),cont=num(budget.getString("contingency","0"));if(training>total*.20)blockers.add("Formation au-dessus de 20 % du budget enregistré.");if(admin>total*.05)blockers.add("Administration au-dessus de 5 % du budget enregistré.");if(cont>total*.10)blockers.add("Contingence au-dessus de 10 % du budget enregistré.");}
 SharedPreferences team=getSharedPreferences("team_capacity",0);if(team.getString("chef","").trim().isEmpty())incomplete.add("Responsable du projet non identifié.");else ready.add("Responsable du projet identifié.");if(team.getString("competences","").trim().isEmpty())incomplete.add("Compétences et expérience de l’équipe à documenter.");else ready.add("Capacité de l’équipe documentée.");
 SharedPreferences timeline=getSharedPreferences("timeline",0);int planned=0;for(int i=0;i<7;i++)if(!timeline.getString("months"+i,"").trim().isEmpty())planned++;if(planned==0)blockers.add("Échéancier du projet non préparé.");else if(planned<7)incomplete.add("Échéancier partiel : "+planned+" / 7 phases planifiées.");else ready.add("Les 7 phases de l’échéancier sont planifiées.");
 SharedPreferences checklist=getSharedPreferences("application_checklist",0);int checked=0;for(int i=0;i<14;i++)if(checklist.getBoolean("i"+i,false))checked++;if(checked<7)blockers.add("Checklist du dossier trop incomplète : "+checked+" / 14.");else if(checked<14)incomplete.add("Checklist du dossier : "+checked+" / 14 éléments cochés.");else ready.add("Checklist du dossier complète : 14 / 14.");}
 private void addGroup(LinearLayout root,String title,List<String> items,String empty){LinearLayout p=Ui.panel(this);p.addView(Ui.text(this,title,20,true));if(items.isEmpty())p.addView(Ui.text(this,empty,14,false));else for(String x:items)p.addView(Ui.text(this,"• "+x,14,false));root.addView(p);}
 private String render(List<String> ready,List<String> incomplete,List<String> blockers){StringBuilder s=new StringBuilder("CULTURE DU QUÉBEC — ÉTAT DU DOSSIER\n\nBLOQUANTS\n");for(String x:blockers)s.append("- ").append(x).append('\n');s.append("\nINCOMPLETS\n");for(String x:incomplete)s.append("- ").append(x).append('\n');s.append("\nPRÊTS\n");for(String x:ready)s.append("- ").append(x).append('\n');s.append("\nIndicateur interne uniquement; les règles officielles demeurent la référence.");return s.toString();}
 private double num(String v){try{return Double.parseDouble(v.replace(',','.'));}catch(Exception e){return 0;}}
}
