package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MappingActivity extends Activity{
    private DocumentStore.Item item; private List<DataNormalizer.ColumnMapping> maps; private DataNormalizer.Sector sector; private final List<RowEditor> editors=new ArrayList<>(); private LinearLayout root;
    private static final class RowEditor{DataNormalizer.ColumnMapping mapping;Spinner target;CheckBox validated;EditText note;TextView status;}
    @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);String id=getIntent().getStringExtra("id");item=DocumentStore.find(this,id);root=Ui.root(this);root.addView(Ui.text(this,"Correspondance à la norme",27,true));if(item==null){root.addView(Ui.text(this,"Document introuvable.",15,false));setContentView(Ui.wrap(this,root));return;}try{sector=DataNormalizer.Sector.valueOf(item.sector);maps=DocumentStore.readMappings(this,item);render();}catch(Exception e){root.addView(Ui.text(this,"Erreur de lecture : "+e.getMessage(),14,false));setContentView(Ui.wrap(this,root));}}
    private void render(){editors.clear();root.removeViews(1,Math.max(0,root.getChildCount()-1));root.addView(Ui.text(this,"Norme de travail : "+sector.label+"\nValidez manuellement chaque proposition. L’application conserve la suggestion automatique, la cible finale, la note humaine et l’horodatage.",14,false));if(maps.isEmpty()){root.addView(Ui.text(this,"Aucun audit détaillé disponible. Réimportez le fichier pour générer la correspondance champ par champ.",14,false));setContentView(Ui.wrap(this,root));return;}int ok=0,check=0,out=0,validated=0;for(DataNormalizer.ColumnMapping m:maps){if(m.humanValidated)validated++;if("CONFORME".equals(m.status)||"VALIDÉ".equals(m.status))ok++;else if("À VALIDER".equals(m.status))check++;else out++;}root.addView(Ui.text(this,"Validés humainement : "+validated+" / "+maps.size()+" · Conformes/validés : "+ok+" · À valider : "+check+" · Hors profil : "+out,15,true));for(DataNormalizer.ColumnMapping m:maps)root.addView(editorCard(m));Button save=Ui.primary(this,"Enregistrer les validations humaines");save.setOnClickListener(v->saveHumanValidation());root.addView(save);Button std=Ui.secondary(this,"Exporter le CSV avec les champs cibles");std.setOnClickListener(v->shareStandardized());root.addView(std);Button audit=Ui.secondary(this,"Exporter / partager l’audit CSV");audit.setOnClickListener(v->shareAudit());root.addView(audit);root.addView(Ui.text(this,"Les profils intégrés servent à préparer et documenter les données. La validation humaine ne constitue pas une certification officielle d’une norme sectorielle.",12,false));setContentView(Ui.wrap(this,root));}
    private View editorCard(DataNormalizer.ColumnMapping m){LinearLayout p=Ui.panel(this);RowEditor e=new RowEditor();e.mapping=m;e.status=Ui.text(this,m.status,16,true);p.addView(e.status);p.addView(Ui.text(this,"Colonne d’origine : "+m.sourceHeader+"\nChamp normalisé : "+m.normalizedHeader+"\nSuggestion automatique : "+blank(m.autoTarget)+"\nExemple avant : "+blank(m.sampleBefore)+"\nExemple après : "+blank(m.sampleAfter)+"\nJustification automatique : "+blank(m.reason),14,false));p.addView(Ui.text(this,"Champ cible final",13,true));ArrayList<String> opts=new ArrayList<>();opts.add("— Aucun champ cible —");opts.addAll(Arrays.asList(sector.suggestedFields));e.target=new Spinner(this);e.target.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,opts));int pos=m.targetField==null||m.targetField.isEmpty()?0:opts.indexOf(m.targetField);e.target.setSelection(Math.max(0,pos));p.addView(e.target);e.validated=new CheckBox(this);e.validated.setText("J’ai validé humainement cette correspondance");e.validated.setChecked(m.humanValidated);p.addView(e.validated);e.note=new EditText(this);e.note.setHint("Note / justification humaine (recommandée si vous modifiez la cible)");e.note.setMinLines(2);e.note.setGravity(Gravity.TOP|Gravity.START);e.note.setText(m.humanNote==null?"":m.humanNote);p.addView(e.note);if(m.validatedAt>0)p.addView(Ui.text(this,"Dernière validation : "+new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.CANADA_FRENCH).format(new Date(m.validatedAt)),12,false));editors.add(e);return p;}
    private void saveHumanValidation(){long now=System.currentTimeMillis();for(RowEditor e:editors){String selected=e.target.getSelectedItemPosition()==0?"":String.valueOf(e.target.getSelectedItem());boolean changed=!Objects.equals(selected,e.mapping.targetField);e.mapping.targetField=selected;e.mapping.humanValidated=e.validated.isChecked();e.mapping.humanNote=e.note.getText().toString().trim();if(e.mapping.humanValidated){e.mapping.status="VALIDÉ";e.mapping.validatedAt=now;if(changed&&e.mapping.humanNote.isEmpty())e.mapping.humanNote="Cible modifiée et validée manuellement.";}else{e.mapping.validatedAt=0L;if(selected.isEmpty())e.mapping.status="HORS PROFIL";else if(selected.equals(e.mapping.normalizedHeader))e.mapping.status="CONFORME";else e.mapping.status="À VALIDER";}}try{DocumentStore.saveMappings(this,item,maps);Toast.makeText(this,"Validations enregistrées et ajoutées au journal d’audit",Toast.LENGTH_LONG).show();render();}catch(Exception ex){new AlertDialog.Builder(this).setTitle("Enregistrement impossible").setMessage(ex.getMessage()).setPositiveButton("OK",null).show();}}
    private void shareAudit(){StringBuilder b=new StringBuilder("source,normalise,suggestion_auto,cible_finale,avant,apres,statut,valide_humainement,note_humaine,date_validation,justification_auto\n");for(DataNormalizer.ColumnMapping m:maps)b.append(q(m.sourceHeader)).append(',').append(q(m.normalizedHeader)).append(',').append(q(m.autoTarget)).append(',').append(q(m.targetField)).append(',').append(q(m.sampleBefore)).append(',').append(q(m.sampleAfter)).append(',').append(q(m.status)).append(',').append(q(Boolean.toString(m.humanValidated))).append(',').append(q(m.humanNote)).append(',').append(q(m.validatedAt==0?"":Long.toString(m.validatedAt))).append(',').append(q(m.reason)).append('\n');shareText("text/csv","Audit de standardisation - "+item.name,b.toString());}
    private void shareStandardized(){try{List<List<String>> rows=DocumentStore.read(this,item);if(rows.isEmpty())throw new Exception("Le document est vide.");List<List<String>> out=new ArrayList<>();List<String> header=new ArrayList<>();for(int i=0;i<rows.get(0).size();i++){if(i<maps.size()&&maps.get(i).targetField!=null&&!maps.get(i).targetField.isEmpty())header.add(maps.get(i).targetField);else if(i<maps.size())header.add(maps.get(i).normalizedHeader);else header.add(rows.get(0).get(i));}out.add(header);for(int i=1;i<rows.size();i++)out.add(new ArrayList<>(rows.get(i)));shareText("text/csv","Catalogue standardisé - "+item.name,SpreadsheetReader.toCsv(out));}catch(Exception ex){new AlertDialog.Builder(this).setTitle("Export impossible").setMessage(ex.getMessage()).setPositiveButton("OK",null).show();}}
    private void shareText(String type,String subject,String text){Intent i=new Intent(Intent.ACTION_SEND);i.setType(type);i.putExtra(Intent.EXTRA_SUBJECT,subject);i.putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(i,"Partager"));}
    private String q(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}private String blank(String s){return s==null||s.isEmpty()?"—":s;}
}
