package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.text.*;import java.util.*;

public class ProjectEvidenceActivity extends Activity{
 private SharedPreferences p;private EditText sharing,partners,activities,issues,expenses,variance,tech,sustain;private TextView autoMetrics,baselineInfo;
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);p=getSharedPreferences("evidence",0);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Preuves et reddition de comptes",27,true));
  LinearLayout auto=Ui.panel(this);auto.addView(Ui.text(this,"Indicateurs automatiques",21,true));auto.addView(Ui.text(this,"Les chiffres ci-dessous sont calculés à partir des catalogues importés et des validations humaines. Une fiche n’est comptée comme entièrement standardisée que lorsque toutes ses colonnes ont une cible et ont été validées humainement.",13,false));autoMetrics=Ui.text(this,"Calcul…",15,true);auto.addView(autoMetrics);baselineInfo=Ui.text(this,"",13,false);auto.addView(baselineInfo);Button baseline=Ui.secondary(this,"Définir l’état actuel comme point de départ");baseline.setOnClickListener(v->{Metrics m=metrics();p.edit().putInt("baselineRows",m.totalRows).putLong("baselineAt",System.currentTimeMillis()).apply();refreshMetrics();Toast.makeText(this,"Point de départ enregistré",Toast.LENGTH_SHORT).show();});auto.addView(baseline);r.addView(auto);
  sharing=f(r,"Modalités de partage / accès / données ouvertes","sharing");partners=f(r,"Partenaires et réutilisations","partners");activities=f(r,"Activités réalisées","activities");issues=f(r,"Problèmes rencontrés et correctifs","issues");expenses=f(r,"Dépenses réelles","expenses");variance=f(r,"Écarts au budget / calendrier","variance");tech=f(r,"Approche technologique et interopérabilité","tech");sustain=f(r,"Développement durable / pérennité","sustain");Button save=Ui.primary(this,"Enregistrer les preuves");save.setOnClickListener(v->save());r.addView(save);Button share=Ui.secondary(this,"Partager le rapport de suivi");share.setOnClickListener(v->{save();shareReport();});r.addView(share);setContentView(Ui.wrap(this,r));refreshMetrics();}
 private EditText f(LinearLayout r,String h,String k){EditText e=Ui.field(this,h,p.getString(k,""));r.addView(e);return e;}
 private void save(){p.edit().putString("sharing",sharing.getText().toString()).putString("partners",partners.getText().toString()).putString("activities",activities.getText().toString()).putString("issues",issues.getText().toString()).putString("expenses",expenses.getText().toString()).putString("variance",variance.getText().toString()).putString("tech",tech.getText().toString()).putString("sustain",sustain.getText().toString()).apply();Toast.makeText(this,"Preuves enregistrées",Toast.LENGTH_SHORT).show();}
 private void refreshMetrics(){Metrics m=metrics();int base=p.getInt("baselineRows",-1);int added=base<0?0:Math.max(0,m.totalRows-base);autoMetrics.setText("Catalogues analysés : "+m.docs+"\nFiches analysées : "+m.totalRows+"\nFiches entièrement standardisées : "+m.standardizedRows+" ("+pct(m.standardizedRows,m.totalRows)+")\nColonnes cartographiées : "+m.mappedColumns+" / "+m.totalColumns+" ("+pct(m.mappedColumns,m.totalColumns)+")\nColonnes validées humainement : "+m.validatedColumns+" / "+m.totalColumns+" ("+pct(m.validatedColumns,m.totalColumns)+")\nCorrections automatiques : "+m.changedCells+"\nCellules vides à vérifier : "+m.emptyCells+"\nDoublons détectés : "+m.duplicates+"\nNouvelles fiches depuis le point de départ : "+added);long at=p.getLong("baselineAt",0);baselineInfo.setText(base<0?"Aucun point de départ enregistré. Définissez-le avant le début du projet pour mesurer automatiquement les nouvelles fiches.":"Point de départ : "+base+" fiche(s) · "+DateFormat.getDateTimeInstance().format(new Date(at)));}
 private void shareReport(){Metrics m=metrics();int base=p.getInt("baselineRows",-1);int added=base<0?0:Math.max(0,m.totalRows-base);String report="Culture du Québec — Rapport de suivi de standardisation\n\nINDICATEURS AUTOMATIQUES\nCatalogues : "+m.docs+"\nFiches analysées : "+m.totalRows+"\nFiches entièrement standardisées : "+m.standardizedRows+" ("+pct(m.standardizedRows,m.totalRows)+")\nColonnes cartographiées : "+m.mappedColumns+" / "+m.totalColumns+"\nColonnes validées humainement : "+m.validatedColumns+" / "+m.totalColumns+"\nNouvelles fiches depuis le point de départ : "+added+"\nCorrections automatiques : "+m.changedCells+"\nCellules vides : "+m.emptyCells+"\nDoublons : "+m.duplicates+"\n\nSUIVI QUALITATIF\nPartage : "+sharing.getText()+"\nPartenaires : "+partners.getText()+"\nActivités : "+activities.getText()+"\nProblèmes : "+issues.getText()+"\nDépenses : "+expenses.getText()+"\nÉcarts : "+variance.getText()+"\nTechnologie : "+tech.getText()+"\nPérennité : "+sustain.getText()+"\n\nDocument de travail — ne constitue pas une certification officielle.";Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,report);startActivity(Intent.createChooser(i,"Partager"));}
 private String pct(int a,int b){return b<=0?"0,0 %":String.format(Locale.CANADA_FRENCH,"%.1f %%",a*100.0/b);}
 private Metrics metrics(){Metrics m=new Metrics();for(DocumentStore.Item d:DocumentStore.list(this)){m.docs++;m.totalRows+=d.rows;m.totalColumns+=d.columns;m.changedCells+=d.changedCells;m.emptyCells+=d.emptyCells;m.duplicates+=d.duplicates;try{java.util.List<DataNormalizer.ColumnMapping> maps=DocumentStore.readMappings(this,d);int mapped=0,validated=0;boolean full=!maps.isEmpty()&&maps.size()==d.columns;for(DataNormalizer.ColumnMapping x:maps){boolean has=x.targetField!=null&&!x.targetField.isBlank();if(has)mapped++;if(has&&x.humanValidated)validated++;if(!has||!x.humanValidated)full=false;}m.mappedColumns+=mapped;m.validatedColumns+=validated;if(full)m.standardizedRows+=d.rows;}catch(Exception ignored){}}return m;}
 static class Metrics{int docs,totalRows,standardizedRows,totalColumns,mappedColumns,validatedColumns,changedCells,emptyCells,duplicates;}
}
