package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import android.widget.*;
public class SectorGuideActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);String s=getIntent().getStringExtra("sector");DataNormalizer.Sector sec;try{sec=DataNormalizer.Sector.valueOf(s);}catch(Exception e){sec=DataNormalizer.Sector.METAMUSIQUE;}LinearLayout r=Ui.root(this);r.addView(Ui.text(this,sec.label,28,true));r.addView(Ui.text(this,"Guide de préparation fondé sur des références publiques. Un champ n’est marqué confirmé que lorsqu’une source sectorielle accessible le justifie; le reste demeure à valider avant une soumission.",13,false));
 LinearLayout status=Ui.panel(this);status.addView(Ui.text(this,"Niveau de preuve",20,true));
 if(sec==DataNormalizer.Sector.METAMUSIQUE){status.addView(Ui.text(this,"RÉFÉRENTIEL PUBLIC DISPONIBLE — INTÉGRATION PARTIELLE",15,true));status.addView(Ui.text(this,"MétaMusique publie un référentiel détaillé avec des règles de saisie. Des champs y sont explicitement qualifiés d’obligatoires, notamment la durée de l’enregistrement, la durée de l’œuvre, les paroles lorsqu’applicables, la version et la mention de contenu explicite. Le référentiel contient aussi des règles pour genres/sous-genres, instrumentation, langues et intervenants.",13,false));Button ref=Ui.secondary(this,"Ouvrir le référentiel MétaMusique");ref.setOnClickListener(v->open("https://metamusique.ca/referentiel/"));status.addView(ref);
 }else if(sec==DataNormalizer.Sector.SCENE){status.addView(Ui.text(this,"RÉFÉRENTIEL DATASCENE IDENTIFIÉ",15,true));status.addView(Ui.text(this,"Le référentiel Datascene concerne les données descriptives des spectacles ayant des représentations. Sa documentation publique précise qu’il est encouragé par le ministère de la Culture et des Communications, sans être obligatoire en soi. Il ne doit pas être confondu avec MétaMusique, qui vise les enregistrements musicaux.",13,false));Button ref=Ui.secondary(this,"Ouvrir Datascene");ref.setOnClickListener(v->open("https://www.datascene.ca/boite-a-outils"));status.addView(ref);
 }else{status.addView(Ui.text(this,"NORME RECONNUE PAR LE PROGRAMME — SCHÉMA COMPLET À VALIDER",15,true));status.addView(Ui.text(this,"Le Programme québécois reconnaît ce secteur pour la standardisation, mais je n’intègre pas de statut obligatoire/recommandé/facultatif tant que la documentation normative complète n’est pas confirmée champ par champ.",13,false));}
 r.addView(status);
 LinearLayout p=Ui.panel(this);p.addView(Ui.text(this,"Champs de travail actuellement intégrés",20,true));for(String f:sec.suggestedFields)p.addView(Ui.text(this,"• "+f,16,false));r.addView(p);
 LinearLayout rules=Ui.panel(this);rules.addView(Ui.text(this,"Règle de validation",20,true));rules.addView(Ui.text(this,"CONFIRMÉ = source publique vérifiée. À VALIDER = correspondance plausible mais non certifiée. HORS PROFIL = aucune correspondance fiable. La validation humaine reste conservée dans le journal d’audit.",13,false));r.addView(rules);
 LinearLayout gov=Ui.panel(this);gov.addView(Ui.text(this,"Programme du Québec",20,true));gov.addView(Ui.text(this,"Le programme vise la standardisation, l’interopérabilité et une meilleure découvrabilité. L’application garde donc la mise à niveau de la base de données au centre du projet plutôt que les fonctions de vitrine ou de carte.",13,false));Button program=Ui.primary(this,"Ouvrir le programme officiel");program.setOnClickListener(v->open("https://www.quebec.ca/culture/aide-financiere/aide-aux-projets-appel/soutien-standardisation-donnees/appel-projets-soutien-standardisation-donnees"));gov.addView(program);r.addView(gov);setContentView(Ui.wrap(this,r));}
 private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}}
}
