package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import android.widget.*;
public class SectorGuideActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);String s=getIntent().getStringExtra("sector");DataNormalizer.Sector sec;try{sec=DataNormalizer.Sector.valueOf(s);}catch(Exception e){sec=DataNormalizer.Sector.METAMUSIQUE;}LinearLayout r=Ui.root(this);r.addView(Ui.text(this,sec.label,28,true));r.addView(Ui.text(this,"Guide de préparation fondé sur des références publiques. Les champs obligatoires ne sont indiqués que lorsqu’une source sectorielle accessible les confirme.",13,false));LinearLayout status=Ui.panel(this);status.addView(Ui.text(this,"Niveau de preuve",20,true));
 if(sec==DataNormalizer.Sector.METAMUSIQUE){status.addView(Ui.text(this,"RÉFÉRENTIEL PUBLIC — INTÉGRATION PARTIELLE",15,true));status.addView(Ui.text(this,"MétaMusique publie un référentiel détaillé. Des règles publiques confirment notamment des champs obligatoires liés à la durée, à la version et au contenu explicite, selon le contexte.",13,false));add(status,"Ouvrir MétaMusique","https://metamusique.ca/referentiel/");}
 else if(sec==DataNormalizer.Sector.SCENE){status.addView(Ui.text(this,"DATASCENE — RÉFÉRENTIEL PUBLIC",15,true));status.addView(Ui.text(this,"Datascene est le référentiel des métadonnées descriptives du spectacle. Il vise l’interopérabilité des systèmes liés aux spectacles et représentations.",13,false));add(status,"Ouvrir Datascene","https://www.datascene.ca/boite-a-outils");}
 else if(sec==DataNormalizer.Sector.CINEMA){status.addView(Ui.text(this,"PANOSCOPE — RÉFÉRENTIEL CINÉMA PUBLIC",15,true));status.addView(Ui.text(this,"Le référentiel Panoscope expose champ par champ les colonnes Obligatoire et Important. Exemples publics confirmés : Version - Titre et Version - Durée sont obligatoires; la langue de version est importante; les règles utilisent notamment ISO 639, ISO 3166-1 et UN/LOCODE selon les champs.",13,false));add(status,"Ouvrir le référentiel cinéma","https://panoscope.ca/referentiel-mcc");}
 else if(sec==DataNormalizer.Sector.LIVRE){status.addView(Ui.text(this,"BTLF / ONIX / THEMA — RÉFÉRENCES PUBLIQUES",15,true));status.addView(Ui.text(this,"La BTLF indique utiliser ONIX pour l’échange des métadonnées du livre et Thema pour les sujets descriptifs. Ses outils publics détaillent aussi les bonnes pratiques de référencement. Les niveaux obligatoires champ par champ demeurent à synchroniser avec le tableau BTLF avant de les imposer automatiquement.",13,false));add(status,"Ouvrir les outils BTLF","https://btlf.ca/outils-et-formations/");}
 else {status.addView(Ui.text(this,"NORME MUSÉALE PUBLIQUE — VERSION INITIALE",15,true));status.addView(Ui.text(this,"La Société des musées du Québec publie une norme de métadonnées pour les expositions en contexte muséal. Elle modélise notamment l’exposition et des classes associées comme les lieux, salles et contributeurs, avec des propriétés normalisées telles que les dates et modalités d’accès.",13,false));add(status,"Ouvrir la norme muséale","https://www.musees.qc.ca/content/download/53638/600658/version/1/file/Norme_exposition_museal.pdf");}
 r.addView(status);LinearLayout p=Ui.panel(this);p.addView(Ui.text(this,"Champs de travail actuellement intégrés",20,true));for(String f:sec.suggestedFields)p.addView(Ui.text(this,"• "+f,16,false));r.addView(p);LinearLayout rules=Ui.panel(this);rules.addView(Ui.text(this,"Règle de validation",20,true));rules.addView(Ui.text(this,"CONFIRMÉ = source publique vérifiée. À VALIDER = correspondance plausible mais non certifiée. HORS PROFIL = aucune correspondance fiable. La validation humaine et son horodatage sont conservés dans l’audit.",13,false));r.addView(rules);LinearLayout gov=Ui.panel(this);gov.addView(Ui.text(this,"Programme du Québec",20,true));gov.addView(Ui.text(this,"Le programme reconnaît cinq normes sectorielles : MétaMusique, Arts de la scène, Cinéma, Livre pour les éditeurs et Exposition en contexte muséal.",13,false));add(gov,"Ouvrir le programme officiel","https://www.quebec.ca/culture/aide-financiere/aide-aux-projets-appel/soutien-standardisation-donnees/appel-projets-soutien-standardisation-donnees");r.addView(gov);setContentView(Ui.wrap(this,r));}
 private void add(LinearLayout p,String label,String u){Button b=Ui.secondary(this,label);b.setOnClickListener(v->open(u));p.addView(b);}private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}}
}
