package quebec.culture.donnees;

import android.content.ContentResolver;
import android.net.Uri;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import java.io.*;import java.nio.charset.*;import java.util.*;import java.util.zip.*;

public final class SpreadsheetReader {
 private SpreadsheetReader(){}
 public static List<List<String>> read(ContentResolver resolver,Uri uri,String name)throws Exception{String lower=name==null?"":name.toLowerCase(Locale.ROOT);try(InputStream in=resolver.openInputStream(uri)){if(in==null)throw new IOException("Impossible d'ouvrir le fichier.");if(lower.endsWith(".xlsx"))return readXlsx(in);if(lower.endsWith(".xls"))throw new IOException("Le format .xls ancien n'est pas pris en charge. Enregistrez le fichier en .xlsx ou .csv.");return readCsv(in);}}
 public static List<List<String>> readCsv(InputStream in)throws IOException{byte[] bytes=in.readAllBytes();String text=decode(bytes);if(text.startsWith("\uFEFF"))text=text.substring(1);char sep=guessSeparator(text);List<List<String>> rows=new ArrayList<>();List<String> row=new ArrayList<>();StringBuilder cell=new StringBuilder();boolean quoted=false;for(int i=0;i<text.length();i++){char c=text.charAt(i);if(c=='"'){if(quoted&&i+1<text.length()&&text.charAt(i+1)=='"'){cell.append('"');i++;}else quoted=!quoted;}else if(c==sep&&!quoted){row.add(cell.toString());cell.setLength(0);}else if((c=='\n'||c=='\r')&&!quoted){if(c=='\r'&&i+1<text.length()&&text.charAt(i+1)=='\n')i++;row.add(cell.toString());cell.setLength(0);if(!allBlank(row))rows.add(row);row=new ArrayList<>();}else cell.append(c);}if(cell.length()>0||!row.isEmpty()){row.add(cell.toString());if(!allBlank(row))rows.add(row);}if(quoted)throw new IOException("CSV invalide : guillemet non fermé.");return rows;}
 private static String decode(byte[] b){if(b.length>=2&&(b[0]&255)==255&&(b[1]&255)==254)return new String(b,2,b.length-2,StandardCharsets.UTF_16LE);if(b.length>=2&&(b[0]&255)==254&&(b[1]&255)==255)return new String(b,2,b.length-2,StandardCharsets.UTF_16BE);if(b.length>=3&&(b[0]&255)==239&&(b[1]&255)==187&&(b[2]&255)==191)return new String(b,3,b.length-3,StandardCharsets.UTF_8);return new String(b,StandardCharsets.UTF_8);}
 private static boolean allBlank(List<String> r){for(String x:r)if(x!=null&&!x.trim().isEmpty())return false;return true;}
 private static char guessSeparator(String text){String[] lines=text.split("\\R",4);String first=lines.length==0?text:lines[0];long commas=first.chars().filter(c->c==',').count(),semis=first.chars().filter(c->c==';').count(),tabs=first.chars().filter(c->c=='\t').count();return tabs>commas&&tabs>semis?'\t':(semis>commas?';':',');}
 public static List<List<String>> readXlsx(InputStream in)throws Exception{Map<String,byte[]> entries=new HashMap<>();try(ZipInputStream zin=new ZipInputStream(in)){ZipEntry e;while((e=zin.getNextEntry())!=null&&!e.isDirectory()){String n=e.getName();if(n.startsWith("xl/")&&(n.endsWith(".xml")||n.endsWith(".rels")))entries.put(n,zin.readAllBytes());}}String sheetName=resolveFirstSheet(entries);byte[] sheet=entries.get(sheetName);if(sheet==null)throw new IOException("Aucune feuille Excel détectée.");List<String> shared=entries.containsKey("xl/sharedStrings.xml")?parseSharedStrings(entries.get("xl/sharedStrings.xml")):List.of();List<List<String>> rows=parseSheet(sheet,shared);if(rows.isEmpty())throw new IOException("La première feuille Excel est vide.");return rows;}
 private static String resolveFirstSheet(Map<String,byte[]> entries)throws Exception{byte[] wb=entries.get("xl/workbook.xml"),rels=entries.get("xl/_rels/workbook.xml.rels");if(wb!=null&&rels!=null){XmlPullParser p=newParser(wb);String rid=null;int event;while((event=p.next())!=XmlPullParser.END_DOCUMENT){if(event==XmlPullParser.START_TAG&&"sheet".equals(p.getName())){for(int i=0;i<p.getAttributeCount();i++){String n=p.getAttributeName(i);if("id".equals(n)||n.endsWith(":id")){rid=p.getAttributeValue(i);break;}}if(rid!=null)break;}}if(rid!=null){XmlPullParser q=newParser(rels);while((event=q.next())!=XmlPullParser.END_DOCUMENT){if(event==XmlPullParser.START_TAG&&"Relationship".equals(q.getName())&&rid.equals(q.getAttributeValue(null,"Id"))){String t=q.getAttributeValue(null,"Target");if(t!=null){if(t.startsWith("/"))t=t.substring(1);else if(!t.startsWith("xl/"))t="xl/"+t.replace("../","");if(entries.containsKey(t))return t;}}}}}if(entries.containsKey("xl/worksheets/sheet1.xml"))return "xl/worksheets/sheet1.xml";return entries.keySet().stream().filter(x->x.startsWith("xl/worksheets/sheet")&&x.endsWith(".xml")).sorted().findFirst().orElse("");}
 private static List<String> parseSharedStrings(byte[] xml)throws Exception{List<String> values=new ArrayList<>();XmlPullParser p=newParser(xml);StringBuilder current=null;int event;while((event=p.next())!=XmlPullParser.END_DOCUMENT){if(event==XmlPullParser.START_TAG&&"si".equals(p.getName()))current=new StringBuilder();else if(event==XmlPullParser.START_TAG&&"t".equals(p.getName())&&current!=null)current.append(p.nextText());else if(event==XmlPullParser.END_TAG&&"si".equals(p.getName())&&current!=null){values.add(current.toString());current=null;}}return values;}
 private static List<List<String>> parseSheet(byte[] xml,List<String> shared)throws Exception{List<List<String>> rows=new ArrayList<>();XmlPullParser p=newParser(xml);List<String> row=null;String type=null;int cellIndex=0,event;while((event=p.next())!=XmlPullParser.END_DOCUMENT){if(event==XmlPullParser.START_TAG&&"row".equals(p.getName())){row=new ArrayList<>();cellIndex=0;}else if(event==XmlPullParser.START_TAG&&"c".equals(p.getName())&&row!=null){String ref=p.getAttributeValue(null,"r");type=p.getAttributeValue(null,"t");int target=ref==null?cellIndex:columnIndex(ref);while(row.size()<target)row.add("");cellIndex=target;}else if(event==XmlPullParser.START_TAG&&("v".equals(p.getName())||"t".equals(p.getName()))&&row!=null){String v=p.nextText();if("s".equals(type)){try{int idx=Integer.parseInt(v);v=idx>=0&&idx<shared.size()?shared.get(idx):v;}catch(Exception ignored){}}else if("b".equals(type))v="1".equals(v)?"TRUE":"FALSE";while(row.size()<=cellIndex)row.add("");row.set(cellIndex,v);}else if(event==XmlPullParser.END_TAG&&"c".equals(p.getName()))cellIndex++;else if(event==XmlPullParser.END_TAG&&"row".equals(p.getName())&&row!=null){if(!allBlank(row))rows.add(row);row=null;}}return rows;}
 private static XmlPullParser newParser(byte[] xml)throws Exception{XmlPullParserFactory f=XmlPullParserFactory.newInstance();f.setNamespaceAware(false);XmlPullParser p=f.newPullParser();p.setInput(new ByteArrayInputStream(xml),"UTF-8");return p;}
 private static int columnIndex(String ref){int n=0;for(int i=0;i<ref.length();i++){char c=ref.charAt(i);if(!Character.isLetter(c))break;n=n*26+(Character.toUpperCase(c)-'A'+1);}return Math.max(0,n-1);}
 public static String toCsv(List<List<String>> rows){StringBuilder out=new StringBuilder("\uFEFF");for(List<String> row:rows){for(int i=0;i<row.size();i++){if(i>0)out.append(',');String value=row.get(i)==null?"":row.get(i);boolean quote=value.contains(",")||value.contains("\"")||value.contains("\n")||value.contains("\r");if(quote)out.append('"').append(value.replace("\"","\"\"")).append('"');else out.append(value);}out.append("\r\n");}return out.toString();}
}
