package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.util.*;
public class StandardizationCenterActivity extends Activity{
 private SharedPreferences p; private Spinner standard; private EditText org,resp,sources,quality,sharing,backup,target,schedule; private TextView readiness;
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);p=getSharedPreferences("standardisation_plan",0);setContentView(build());}
 @Override protected void onResume(){super.onResume();if(readiness!=null)refreshReadiness();}
 private android.view.View build(){LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Centre de standardisation",28,true));r.addView(Ui.text(this,"Outil de préparation, de mise à niveau et de suivi des données culturelles.",14,false));LinearLayout ready=Ui.panel(this);ready.addView(Ui.text(this,"Tableau de préparation",21,true));readiness=Ui.text(this,"Calcul…",15,true);ready.addView(readiness);ready.addView(Ui.text(this,"Cet indicateur mesure la préparation interne. Il ne constitue pas une décision d’admissibilité ni une promesse de financement.",12,false));r.addView(ready);
 LinearLayout elig=Ui.panel(this);elig.addView(Ui.text(this,"0 · Admissibilité et évaluation",21,true));Button eb=Ui.primary(this,"Vérifier l’admissibilité au programme");eb.setOnClickListener(v->startActivity(new Intent(this,EligibilityActivity.class)));elig.addView(eb);Button eval=Ui.secondary(this,"Ouvrir la grille d’évaluation pondérée");eval.setOnClickListener(v->startActivity(new Intent(this,EvaluationCriteriaActivity.class)));elig.addView(eval);r.addView(elig);
 LinearLayout n=Ui.panel(this);n.addView(Ui.text(this,"1 · Norme sectorielle",21,true));String[] a={"MétaMusique","Arts de la scène","Cinéma","Livre — pour les éditeurs","Exposition dans un contexte muséal"};standard=new Spinner(this);standard.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));standard.setSelection(p.getInt("standard",0));n.addView(standard);Button guide=Ui.secondary(this,"Voir le guide et le niveau de preuve");guide.setOnClickListener(v->{String[] c={"METAMUSIQUE","SCENE","CINEMA","LIVRE","MUSEE"};Intent i=new Intent(this,SectorGuideActivity.class);i.putExtra("sector",c[standard.getSelectedItemPosition()]);startActivity(i);});n.addView(guide);r.addView(n);
 LinearLayout flow=Ui.panel(this);flow.addView(Ui.text(this,"2 · Parcours technique",21,true));flow.addView(Ui.text(this,"IMPORTER → CARTOGRAPHIER → NORMALISER → VALIDER → EXPORTER → MESURER",14,true));Button timeline=Ui.primary(this,"Planifier l’échéancier");timeline.setOnClickListener(v->startActivity(new Intent(this,ProjectTimelineActivity.class)));flow.addView(timeline);r.addView(flow);
 LinearLayout plan=Ui.panel(this);plan.addView(Ui.text(this,"3 · Plan de gestion des données",21,true));org=f(plan,"Organisation","org");resp=f(plan,"Responsable des données","resp");sources=f(plan,"Sources et provenance","sources");quality=f(plan,"Contrôle qualité","quality");sharing=f(plan,"Partage / données ouvertes / partenaires","sharing");backup=f(plan,"Sauvegardes et conservation","backup");target=f(plan,"Cible mesurable","target");schedule=f(plan,"Échéancier global ≤ 12 mois","schedule");Button save=Ui.primary(this,"Enregistrer le plan");save.setOnClickListener(v->{save();refreshReadiness();});plan.addView(save);r.addView(plan);
 LinearLayout dossier=Ui.panel(this);dossier.addView(Ui.text(this,"4 · Dossier de projet",21,true));Button budget=Ui.primary(this,"Calculateur budgétaire");budget.setOnClickListener(v->startActivity(new Intent(this,BudgetActivity.class)));dossier.addView(budget);Button checklist=Ui.secondary(this,"Liste de contrôle");checklist.setOnClickListener(v->startActivity(new Intent(this,ApplicationChecklistActivity.class)));dossier.addView(checklist);Button pieces=Ui.secondary(this,"Pièces officielles à fournir");pieces.setOnClickListener(v->startActivity(new Intent(this,SupportingDocumentsActivity.class)));dossier.addView(pieces);Button team=Ui.secondary(this,"Équipe et capacité");team.setOnClickListener(v->startActivity(new Intent(this,TeamCapacityActivity.class)));dossier.addView(team);Button readinessB=Ui.primary(this,"Contrôle final du dossier");readinessB.setOnClickListener(v->startActivity(new Intent(this,GrantReadinessActivity.class)));dossier.addView(readinessB);Button pkg=Ui.primary(this,"Générer le dossier consolidé");pkg.setOnClickListener(v->{save();startActivity(new Intent(this,GrantPackageActivity.class));});dossier.addView(pkg);r.addView(dossier);
 LinearLayout report=Ui.panel(this);report.addView(Ui.text(this,"5 · Mesures et reddition",21,true));Button evidence=Ui.primary(this,"Preuves et résultats");evidence.setOnClickListener(v->startActivity(new Intent(this,ProjectEvidenceActivity.class)));report.addView(evidence);Button follow=Ui.secondary(this,"Préparer le suivi obligatoire des résultats");follow.setOnClickListener(v->startActivity(new Intent(this,ReportingActivity.class)));report.addView(follow);r.addView(report);refreshReadiness();return Ui.wrap(this,r);}
 private EditText f(LinearLayout x,String h,String k){EditText e=Ui.field(this,h,p.getString(k,""));x.addView(e);return e;}
 private void save(){p.edit().putInt("standard",standard.getSelectedItemPosition()).putString("org",org.getText().toString()).putString("resp",resp.getText().toString()).putString("sources",sources.getText().toString()).putString("quality",quality.getText().toString()).putString("sharing",sharing.getText().toString()).putString("backup",backup.getText().toString()).putString("target",target.getText().toString()).putString("schedule",schedule.getText().toString()).apply();}
 private void refreshReadiness(){if(readiness==null)return;int done=0,total=0;String[] keys={"org","resp","sources","quality","sharing","backup","target","schedule"};for(String k:keys){total++;if(!p.getString(k,"").trim().isEmpty())done++;}SharedPreferences c=getSharedPreferences("application_checklist",0);for(int i=0;i<14;i++){total++;if(c.getBoolean("i"+i,false))done++;}total+=3;List<DocumentStore.Item> docs=DocumentStore.list(this);if(!docs.isEmpty())done++;boolean mapped=false,validated=false;for(DocumentStore.Item d:docs)try{for(DataNormalizer.ColumnMapping m:DocumentStore.readMappings(this,d)){if(m.targetField!=null&&!m.targetField.isBlank())mapped=true;if(m.humanValidated)validated=true;}}catch(Exception ignored){}if(mapped)done++;if(validated)done++;int basePct=(int)Math.round(done*100.0/Math.max(1,total));int elig=EligibilityActivity.completedCount(this);int pieces=SupportingDocumentsActivity.completedCount(this);readiness.setText("Préparation technique : "+basePct+" %\nAdmissibilité confirmée : "+elig+" / 24\nPièces suivies : "+pieces+" / "+SupportingDocumentsActivity.totalCount()+"\nCatalogues : "+docs.size()+" · Cartographie : "+(mapped?"oui":"non")+" · Validation humaine : "+(validated?"oui":"non"));}
}
