package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;
public class SupportingDocumentsActivity extends Activity{
 private SharedPreferences p;
 private final String[] keys={"quote","capacity","budget","timeline","data_plan","catalog_sample","mapping_audit","team","risks","open_data","official_forms"};
 private final String[] labels={"Devis d’un fournisseur ou estimation détaillée","Preuve de capacité interne si le travail est réalisé à l’interne","Budget détaillé","Échéancier du projet","Plan de gestion des données","Échantillon ou inventaire du catalogue à mettre à niveau","Audit de cartographie / correspondance des champs","Description de l’équipe et des compétences","Registre des risques et mesures de mitigation","Plan de partage ou données ouvertes si applicable","Formulaires et gabarits officiels remplis"};
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);p=getSharedPreferences("supporting_docs",0);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Pièces justificatives",27,true));r.addView(Ui.text(this,"Cette liste distingue les pièces qui doivent provenir de l’organisation ou d’un fournisseur, celles que l’application peut préparer et celles qui doivent être vérifiées dans les formulaires officiels.",13,false));addSection(r,"À FOURNIR PAR L’ORGANISATION / FOURNISSEUR",0,2);addSection(r,"PRÉPARABLES DANS L’APPLICATION",2,10);addSection(r,"À VÉRIFIER DANS LES FORMULAIRES OFFICIELS",10,11);TextView status=Ui.text(this,"",15,true);r.addView(status);Button save=Ui.primary(this,"Enregistrer et recalculer");save.setOnClickListener(v->{refresh(status);Toast.makeText(this,"Pièces enregistrées",Toast.LENGTH_SHORT).show();});r.addView(save);Button readiness=Ui.secondary(this,"Retour à l’état du dossier");readiness.setOnClickListener(v->startActivity(new Intent(this,GrantReadinessActivity.class)));r.addView(readiness);refresh(status);setContentView(Ui.wrap(this,r));}
 private void addSection(LinearLayout root,String title,int start,int end){LinearLayout box=Ui.panel(this);box.addView(Ui.text(this,title,19,true));for(int i=start;i<end;i++){CheckBox c=new CheckBox(this);c.setText(labels[i]);c.setChecked(p.getBoolean(keys[i],false));final String k=keys[i];c.setOnCheckedChangeListener((b,v)->p.edit().putBoolean(k,v).apply());box.addView(c);}root.addView(box);}
 private void refresh(TextView t){int done=0;for(String k:keys)if(p.getBoolean(k,false))done++;t.setText("Pièces marquées disponibles : "+done+" / "+keys.length+"\nStatut interne : "+(done==keys.length?"jeu de pièces complet":"pièces à compléter"));}
 public static boolean isComplete(android.content.Context c){SharedPreferences p=c.getSharedPreferences("supporting_docs",0);String[] k={"quote","capacity","budget","timeline","data_plan","catalog_sample","mapping_audit","team","risks","open_data","official_forms"};for(String x:k)if(!p.getBoolean(x,false))return false;return true;}
 public static int completedCount(android.content.Context c){SharedPreferences p=c.getSharedPreferences("supporting_docs",0);String[] k={"quote","capacity","budget","timeline","data_plan","catalog_sample","mapping_audit","team","risks","open_data","official_forms"};int n=0;for(String x:k)if(p.getBoolean(x,false))n++;return n;}
}
