package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;
public class SupportingDocumentsActivity extends Activity{
 private SharedPreferences p;
 private final String[] keys={"signed_aide_memoire","project_description","detailed_budget","partner_letters","team","timeline","data_plan","supplier_quotes","signed_conditions","financial_statements","board_list","shareholders_if_private"};
 private final String[] labels={"Aide-mémoire officiel dûment signé","Description du projet selon le gabarit DOCX officiel","Budget détaillé selon le gabarit XLSM officiel","Lettres d’engagement des partenaires et valeur de leur contribution, s’il y a lieu","Présentation de l’équipe et des sous-traitants avec expérience et compétences","Calendrier de réalisation détaillé, maximum 12 mois","Plan de gestion des données descriptives selon le gabarit officiel","Soumissions de fournisseurs, le cas échéant","Conditions d’octroi de l’aide financière dûment signées","États financiers les plus récents, approuvés et signés","Liste à jour du conseil d’administration avec présidence et adresse courriel","Entreprise privée seulement : actionnaires, droits de vote, citoyenneté et domicile au Québec"};
 @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);p=getSharedPreferences("supporting_docs",0);LinearLayout r=Ui.root(this);r.addView(Ui.text(this,"Pièces officielles du dossier",27,true));r.addView(Ui.text(this,"Liste alignée sur les pièces actuellement demandées par le ministère. Les éléments conditionnels doivent être cochés seulement lorsqu’ils s’appliquent à votre organisation.",13,false));addSection(r,"DOCUMENTS OFFICIELS À SIGNER / REMPLIR",0,4);addSection(r,"DOCUMENTS TECHNIQUES ET DE PROJET",4,8);addSection(r,"DOCUMENTS ADMINISTRATIFS",8,12);TextView status=Ui.text(this,"",15,true);r.addView(status);Button save=Ui.primary(this,"Enregistrer et recalculer");save.setOnClickListener(v->{refresh(status);Toast.makeText(this,"État des pièces enregistré",Toast.LENGTH_SHORT).show();});r.addView(save);Button readiness=Ui.secondary(this,"Retour à l’état du dossier");readiness.setOnClickListener(v->startActivity(new Intent(this,GrantReadinessActivity.class)));r.addView(readiness);r.addView(Ui.text(this,"Important : lettres de partenaires, soumissions et renseignements sur l’actionnariat sont conditionnels. Vérifiez le formulaire di@pason et les gabarits officiels avant le dépôt.",12,false));refresh(status);setContentView(Ui.wrap(this,r));}
 private void addSection(LinearLayout root,String title,int start,int end){LinearLayout box=Ui.panel(this);box.addView(Ui.text(this,title,19,true));for(int i=start;i<end;i++){CheckBox c=new CheckBox(this);c.setText(labels[i]);c.setChecked(p.getBoolean(keys[i],false));final String k=keys[i];c.setOnCheckedChangeListener((b,v)->p.edit().putBoolean(k,v).apply());box.addView(c);}root.addView(box);}
 private void refresh(TextView t){int done=completedCount(this);t.setText("Pièces marquées disponibles : "+done+" / "+keys.length+"\nStatut interne : "+(done==keys.length?"toutes les pièces suivies sont disponibles":"pièces à compléter ou à confirmer"));}
 public static boolean isComplete(android.content.Context c){SharedPreferences p=c.getSharedPreferences("supporting_docs",0);String[] k={"signed_aide_memoire","project_description","detailed_budget","partner_letters","team","timeline","data_plan","supplier_quotes","signed_conditions","financial_statements","board_list","shareholders_if_private"};for(String x:k)if(!p.getBoolean(x,false))return false;return true;}
 public static int completedCount(android.content.Context c){SharedPreferences p=c.getSharedPreferences("supporting_docs",0);String[] k={"signed_aide_memoire","project_description","detailed_budget","partner_letters","team","timeline","data_plan","supplier_quotes","signed_conditions","financial_statements","board_list","shareholders_if_private"};int n=0;for(String x:k)if(p.getBoolean(x,false))n++;return n;}
 public static int totalCount(){return 12;}
}
